### ISSUE TITLE
Error when running toga.py

### ISSUE THREAD

**Issue by soneyahossain** [microsoft/toga#2]
Hi, 

First of all, thanks for publicly sharing this very interesting work. 

I am using Python version: 3.9.5. All requirements installed. I can run rq1.py successfully. However, whenever I try to run toga.py, I get the following error. Any help is highly appreciated, 

```
python toga.py data/inputs_omc.csv data/meta.csv

preparing exception model inputs
05/19/2022 10:17:32 - WARNING - __main__ -   Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
Some weights of the model checkpoint at microsoft/codebert-base were not used when initializing RobertaForSequenceClassification: ['pooler.dense.weight', 'pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at microsoft/codebert-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
05/19/2022 10:17:34 - INFO - __main__ -   Training/evaluation parameters Namespace(data_dir='./', model_type='roberta', model_name_or_path='microsoft/codebert-base', task_name='exception_classifier', output_dir='./model/exception_classifier', config_name='', tokenizer_name='', cache_dir='', max_seq_length=200, do_train=False, do_eval=False, do_predict=True, evaluate_during_training=False, do_lower_case=False, per_gpu_train_batch_size=32, per_gpu_eval_batch_size=256, gradient_accumulation_steps=1, learning_rate=1e-05, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=8.0, max_steps=-1, warmup_steps=0, logging_steps=50, save_steps=50, eval_all_checkpoints=True, no_cuda=False, overwrite_output_dir=True, overwrite_cache=False, seed=42, fp16=False, fp16_opt_level='O1', local_rank=-1, server_ip='', server_port='', train_file='train.txt', dev_file='valid.txt', test_file='except_model_inputs.csv', pred_model_dir='model/exceptions/pretrained', test_result_dir='test_results.csv', print_results=False, n_gpu=0, device=device(type='cpu'), output_mode='classification', start_epoch=0, start_step=0)
testing
Traceback (most recent call last):
  File "/home/user/toga/./model/exceptions/run_classifier.py", line 656, in <module>
    main()
  File "/home/user/toga/./model/exceptions/run_classifier.py", line 649, in main
    model = model_class.from_pretrained(args.pred_model_dir)
  File "/home/user/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1298, in from_pretrained
    raise EnvironmentError(
**OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index', 'flax_model.msgpack'] found in directory model/exceptions/pretrained or `from_tf` and `from_flax` set to False.**
Traceback (most recent call last):
  File "/home/user/toga/toga.py", line 210, in <module>
    main()
  File "/home/user/toga/toga.py", line 46, in main
    results = pd.read_csv('exception_preds.csv', index_col=False)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/user/.local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/user/.local/lib/python3.9/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'exception_preds.csv'
```

**Comment by gryan11** [comment]
If you see this error you need to download the pytorch models. Please follow the directions under the Models section of the Readme.

**Comment by soneyahossain** [comment]
Thanks, Gabriel. Actually, I copied the files from google drive, but I did not rename them. After renaming them to pytorch_model.bin ( I guess I missed that part), I was able to run toga. Thank you so much.
